<?php

// Make sure no one attempts to run this script "directly"
if (!defined('DB_CONFIG'))
	exit;

// These are the regular, "non-SEF" URLs (you probably don't want to edit these)
$url_scheme = array(
	'change_email'					=>	'profile.php?action=change_email&amp;id=$1',
	'change_email_key'				=>	'profile.php?action=change_email&amp;id=$1&amp;key=$2',
	'change_password'				=>	'profile.php?action=change_pass&amp;id=$1',
	'change_password_key'			=>	'profile.php?action=change_pass&amp;id=$1&amp;key=$2',
	'delete_user'					=>	'profile.php?action=delete_user&amp;id=$1',
	'delete_avatar'					=>	'profile.php?action=delete_avatar&amp;id=$1&amp;csrf_token=$2',
	'edit'							=>	'edit.php?id=$1',
	'email'							=>	'misc.php?email=$1',
	'help'							=>	'help.php?section=$1',
	'index'							=>	'index.php',
	'login'							=>	'login.php',
	'logout'						=>	'login.php?action=out&amp;id=$1&amp;csrf_token=$2',
	'mark_read'						=>	'misc.php?action=markread&amp;csrf_token=$1',
	'mark_forum_read'				=>	'misc.php?action=markforumread&amp;fid=$1&amp;csrf_token=$2',
	'opensearch'					=>	'misc.php?action=opensearch',
	'profile_about'					=>	'profile.php?section=about&id=$1',
	'profile_identity'				=>	'profile.php?section=identity&id=$1',
	'profile_settings'				=>	'profile.php?section=settings&id=$1',
	'profile_avatar'				=>	'profile.php?section=avatar&id=$1',
	'profile_signature'				=>	'profile.php?section=signature&id=$1',
	'profile_admin'					=>	'profile.php?section=admin&id=$1',
	'profile_invite'				=>	'profile.php?section=invite&id=$1',
	'userlist'						=>	'userlist.php',
	'register'						=>	'register.php',
	'report'						=>	'misc.php?report=$1',
	'request_password'				=>	'login.php?action=forget',
	'rules'							=>	'misc.php?action=rules',
	'user'							=>	'profile.php?id=$1',
	'page'							=>	'&amp;p=$1',
	'admin_access'					=>	'admin/access.php',
	'admin_index'					=>	'admin/index.php',
	'admin_extensions_manage'		=>	'admin/extensions.php?section=manage',
	'admin_extensions_hotfixes'		=>	'admin/extensions.php?section=hotfixes',
	'admin_groups'					=>	'admin/groups.php',
	'admin_loader'					=>	'admin/loader.php',
	'admin_permissions'				=>	'admin/permissions.php',
	'admin_settings_setup'			=>	'admin/settings.php?section=setup',
	'admin_settings_features'		=>	'admin/settings.php?section=features',
	'admin_settings_content'		=>	'admin/settings.php?section=content',
	'admin_settings_email'			=>	'admin/settings.php?section=email',
	'admin_settings_announcements'	=>	'admin/settings.php?section=announcements',
	'admin_settings_registration'	=>	'admin/settings.php?section=registration',
	'admin_settings_communications'	=>	'admin/settings.php?section=communications',
	'admin_settings_maintenance'	=>	'admin/settings.php?section=maintenance',
	'admin_departments'				=>	'admin/departments.php',
	'admin_positions'				=>	'admin/positions.php',
	'admin_users'					=>	'admin/users.php',
	'admin_new_user'				=>	'admin/new_user.php',
	'apps_management'				=>	'apps/management.php',
	'apps_management_action'		=>	'apps/management.php?action=$1&id=$2',
	'inc_ajax_update_apn'			=>	'include/ajax/update_apn.php',

);
